[tools]
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"

[env]
'_'.file = ["~/.config/mise/.env.mcp", "{{ config_root }}/.env.mcp"]
